using System.Text.Json.Serialization;

namespace AgUiProtocol;

/// <summary>
/// Parameters deserialized from the agent's TOOL_CALL_ARGS for the
/// <c>generate_ui</c> tool (Pillar 3B — Fully Open-Ended Generative UI).
///
/// The LLM generates a complete, self-contained HTML document and passes it
/// as the <see cref="HtmlContent"/> argument when it calls the tool.
/// CopilotKit streams the argument tokens via TOOL_CALL_ARGS; the
/// <c>event_generator</c> in <c>main.py</c> buffers all deltas and emits
/// one complete event before TOOL_CALL_END so that JSON deserialization
/// receives a valid document.
///
/// Wire format sent by the Python agent:
/// <code>
/// {
///   "html_content": "&lt;!DOCTYPE html&gt;&lt;html&gt;...&lt;/html&gt;",
///   "title":        "Taco Rain"
/// }
/// </code>
///
/// <c>GeneratedUiFrame</c> receives this as its <c>Params</c> parameter and
/// injects <see cref="HtmlContent"/> into a double-sandboxed iframe via
/// <c>generatedUiBridge.js</c>.
/// </summary>
public class GeneratedUiParams
{
    /// <summary>
    /// The complete, self-contained HTML document generated by the agent.
    /// Must start with <c>&lt;!DOCTYPE html&gt;</c> and contain all CSS and
    /// JavaScript inline — no external URLs of any kind.
    /// </summary>
    [JsonPropertyName("html_content")]
    public string HtmlContent { get; set; } = string.Empty;

    /// <summary>
    /// Short display title shown in the widget title bar.
    /// Populated by the agent from the user's request, e.g. "Taco Rain".
    /// </summary>
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;
}
